version: '3'

services:
  rdkit-search-api:
    image: search-api
    build:
      context: ./Api
      dockerfile: RDKit/Dockerfile
    ports:
    - "5000:5000"
    environment:
    - ASPNETCORE_URLS=http://+:5000
    - postgres_connection=User ID=postgres;Host=rdkit-postgres;Port=5432;Database=simsearch;Pooling=true;
    # network_mode: "host"
  rdkit-postgres:
    image: rdkit-postgres
    container_name: rdkit-postgres
    build:
      context: ./Docker.rdkit
      dockerfile: dockerfile
    ports:
    - "5432:5432"
    # network_mode: "host"
