version: '3'

services:
  rdkit-search-api:
    image: search-api
    build:
      context: ./Api
      dockerfile: ./RDKit/Dockerfile
    ports:
    - "5000:5000"
    environment:
    # - http_proxy='http://10.3.80.80:3128'
    # - https_proxy='http://10.3.80.80:3128'
    - ASPNETCORE_URLS=http://+:5000
    - postgres_connection=User ID=postgres;Host=rdkit-postgres;Port=5432;Database=simsearch;Pooling=true;
    - mongo_connection=mongodb://mongo:27017
    # network_mode: "host"
  rdkit-postgres:
    image: rdkit-postgres
    container_name: rdkit-postgres
    build:
      context: ./Docker.rdkit
      dockerfile: dockerfile
    ports:
    - "5432:5432"
    volumes:
    - ~/rdkit-postgres-data:/var/lib/postgresql/data
    # environment:
    # - http_proxy=http://10.3.80.80:3128
    # - https_proxy=http://10.3.80.80:3128
    # network_mode: "host"
  java-oplusd:
    image: java-oplusd
    container_name: java-oplusd
    build:
      context: ./JavaOPlusD
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - ora_connection=jdbc:oracle:thin:@10.3.80.181:1521:chemspace
      # - http_proxy=http://10.3.80.80:3128
      # - https_proxy=http://10.3.80.80:3128
  oplusd-search-api:
    image: oplusd-search-api
    build:
      context: ./Api
      dockerfile: ./JavaOPlusD/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - java_oplusd_url=http://java-oplusd:8080
      # - http_proxy=http://10.3.80.80:3128
      # - https_proxy=http://10.3.80.80:3128