version: '3'

services:
  rdkit-search-api:
    image: search-api
    build:
      context: ./Api
      dockerfile: ./RDKit/Dockerfile
    ports:
    - "5000:5000"
    environment:
    # - http_proxy='http://10.3.80.80:3128'
    # - https_proxy='http://10.3.80.80:3128'
    - ASPNETCORE_URLS=http://+:5000
    - postgres_connection=User ID=postgres;Host=rdkit-postgres;Port=5432;Database=simsearch;Pooling=true;
    - mongo_connection=mongodb://search_350m:a87s9h2uf3F2@mongo:27017
    # network_mode: "host"
  rdkit-postgres:
    image: rdkit-postgres
    container_name: rdkit-postgres
    build:
      context: ./Docker.Rdkit
      dockerfile: dockerfile
    ports:
    - "5432:5432"
    # volumes:
    # - ~/rdkit-postgres-data:/var/lib/postgresql/data
    # environment:
    # - http_proxy=http://10.3.80.80:3128
    # - https_proxy=http://10.3.80.80:3128
    # network_mode: "host"
  java-oplusd:
    image: java-oplusd
    container_name: java-oplusd
    build:
      context: ./JavaOPlusD
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - ora_connection=jdbc:oracle:thin:@10.3.80.181:1521:chemspace
      - ora_user=c$dcischem
      - ora_pass=y3wxf1o(PLpt
      # - http_proxy=http://10.3.80.80:3128
      # - https_proxy=http://10.3.80.80:3128
  oplusd-search-api:
    image: oplusd-search-api
    build:
      context: ./Api
      dockerfile: ./JavaOPlusD/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - java_oplusd_url=http://java-oplusd:8080
      # - http_proxy=http://10.3.80.80:3128
      # - https_proxy=http://10.3.80.80:3128
  mongo:
    image: mongo:3.6
    container_name: mongo
    command: mongod --auth
    ports: 
      - "27017:27017"
    volumes:
      - "~/mongo-data:/data/db"
  mongo-bootstrap:
    image: mongo-bootstrap
    build: 
      context: ./Api
      dockerfile: ./Mongo/bootstrap.dockerfile
    volumes:
      - "~/kos/m337:/data"
