version: '3'

services:
  https-portal-prod:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - prod-v2-uorsy
    restart: always
    environment:
      DOMAINS: 'api.uorsy.com -> http://prod-v2-uorsy'
      STAGE: 'production'
  prod-v2-uorsy:
    image: uorsy-search
    build:
      context: ./ApiV2
      dockerfile: ./Uorsy/Dockerfile
    environment:
    - ASPNETCORE_URLS=http://+:80
    - postgres_connection=User ID=postgres;Host=rdkit-postgres;Port=5432;Database=uorsy;Pooling=true;
    - path_to_csv_source=/data/mols.csv
    - path_to_price_cats=/data/pricingCat.csv
    - smtp_address=mail.uorsy.com
    - smtp_port=465
    - "smtp_password=]$$zqO$$sY)FKE"
    - smtp_username=no-reply@uorsy.com
    - email_from=no-reply@uorsy.com
    - inquiry_notification_email=screenlibs@uorsy.com
    volumes:
    - "/home/kostya/logs/uorsy-prod:/log"
    - "/home/kostya/data/uorsy-prod:/data"
  # test-v2-uorsy:
  #   image: uorsy-search
  #   build:
  #     context: ./ApiV2
  #     dockerfile: ./Uorsy/Dockerfile
  #   ports:
  #   - "8081:5000"
  #   environment:
  #   - ASPNETCORE_URLS=http://+:80
  #   - postgres_connection=User ID=postgres;Host=rdkit-postgres;Port=5432;Database=uorsy;Pooling=true;
  #   - path_to_csv_source=/data/mols.csv
  #   - path_to_price_cats=/data/pricingCat.csv
  #   - smtp_address=mail.uorsy.com
  #   - smtp_port=587
  #   - "smtp_password=]$$zqO$$sY)FKE"
  #   - smtp_username=no-reply@uorsy.com
  #   - email_from=no-reply@uorsy.com
  #   - inquiry_notification_email=koskokos.dev@gmail.com
  #   volumes:
  #   - "/home/kostya/logs/uorsy-test:/log"
  #   - "/home/kostya/data/uorsy-test:/data"
  rdkit-postgres:
    image: rdkit-postgres
    container_name: rdkit-postgres
    build:
      context: ./Docker.Rdkit
      dockerfile: Dockerfile
    # volumes:
    # - "/home/kostya/data/rdkit-postgres-data:/var/lib/postgresql/data"
